# Generated by Django 2.0.2 on 2018-02-14 07:38

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HandbookArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('urlname', models.CharField(blank=True, max_length=200)),
                ('main_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ideas', models.ManyToManyField(blank=True, to='semsite.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('translations', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='handbookarticle',
            name='ideas',
            field=models.ManyToManyField(blank=True, to='semsite.Idea'),
        ),
        migrations.AddField(
            model_name='handbookarticle',
            name='literature',
            field=models.ManyToManyField(blank=True, to='semsite.Publication'),
        ),
        migrations.AddField(
            model_name='handbookarticle',
            name='terms',
            field=models.ManyToManyField(blank=True, to='semsite.Term'),
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(blank=True, to='semsite.Publication'),
        ),
    ]
