# Generated by Django 2.0.2 on 2018-02-13 18:48

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookarticle',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
