# Generated by Django 2.0.2 on 2018-02-14 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookarticle',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
