# Generated by Django 2.0.2 on 2018-02-16 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

        dependencies = [
                        ('publications_bootstrap', '0005_alter_pdf_field'),
                        ('semsite', '0001_initial')
        ]
        operations = [
                            migrations.CreateModel(
                                            name='Author',
                                                        fields=[
                                                                            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                                                                            ('first_name', models.CharField(max_length=30)),
                                                                                                            ('last_name', models.CharField(max_length=30)),
                                                                                                                            ('bio', models.TextField(blank=True)),
                                                                                                                                            ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                                                                                                                                                            ('birthdate', models.DateField(default=django.utils.timezone.now)),
                                                                                                                                                                            ('publications', models.ManyToManyField(blank=True, to='publications_bootstrap.Publication')),
                                                                                                                                                                                        ],
                                                                ),
                                ]
