# Generated by Django 2.0.2 on 2018-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='letter',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
    ]
