# Generated by Django 2.0.2 on 2018-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='translations',
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text='Если у термина несколько названий, разделяйте их запятыми', max_length=200, verbose_name='Название'),
        ),
    ]
