# Generated by Django 2.0.3 on 2018-03-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0005_auto_20180315_0928'),
        ('semsite', '0003_term_letter'),
    ]

    operations = [
    ]
