# Generated by Django 2.0.3 on 2018-03-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0006_merge_20180316_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='letter',
        ),
    ]
