# Generated by Django 2.0.3 on 2018-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0012_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookarticle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
