# Generated by Django 2.0.3 on 2018-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0013_auto_20180318_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='slug',
        ),
    ]
