# Generated by Django 2.0.2 on 2018-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semsite', '0017_auto_20180318_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookarticle',
            name='chapters',
            field=models.TextField(default='Глава 1, Глава 2', help_text='Названия разделов должны писаться через запятую', verbose_name='Оглавление'),
            preserve_default=False,
        ),
    ]
